const JOBS_DATA = [
    {
        id: '1',
        title: 'Frontend Developer',
        company:'Vaarst',
        description: 'We are looking for a skilled Frontend Developer to be a part our growing web platform team. You will be facing interesting problems that require skill and creativity. As a team we are passionate about our company’s future and work hard to see the results of our efforts changing our industry. We are small enough that everybody makes a difference but big enough to provide variety of work and strong in-house expertise. We work together and celebrate our successes together.',
        skills: ['TypeScript', 'React', 'Three.js'],
        type: ['Full Time'],
        location: 'Bristol BS1',
    },
    {
        id: '2',
        title: 'Frontend Developer',
        company:'Develop',
        description: 'We are recruiting on behalf of our client who are a global digital agency, who are looking to hire multiple React Developers on a contract basis for various long term projects. They need someone who is a strong react developer but also has understanding of PHP so that you can fix APIs',
        skills: ['React', 'Typescript', 'Gatsby'],
        type: ['Remote', 'Parmanent'],
        location: 'Bristol',
    },
    {
        id: '3',
        title: 'Frontend Developer',
        company:'Dotmatics',
        description: 'Collaborate with product management, application science and support stakeholders to develop and maintain product suite. Deliver high quality clean code and technical documentation. Solve challenging customer issues using a rapid delivery model. Develop prototype/proof-of-concept implementations for early feedback.Pursue continual improvement in all aspects of the software and its development lifecycle',
        skills: ['JavaScript', 'React'],
        type: ['Remote'],
        location: 'Weschester',
    },
    {
        id: '4',
        title: 'Backend Developer',
        company:'Clowdr CIC',
        description: 'Our ideal candidate for this position is a is an experienced developer with a particular interest in back-end design and implementation. You should have an eye for what looks good and an instinct for good user experience.',
        skills: ['Typescript', 'React', 'GraphQL'],
        type: ['Full Time'],
        location: 'Liverpool',
    },
    {
        id: '5',
        title: 'Software Engineer',
        company:'Econscia',
        description: 'You will be working on different challenges day to day. This could be getting deep into research from which you’ll develop prototypes and POCs, working on key features alongside the team, or contributing to a clean, enterprise-grade SaaS application with security by design. We hope you can work with us to own key aspects of econscia’s analytics engine, but could also roll up your sleeves and dive into research, onboard customers, or dabble in unfamiliar technologies quickly - when the job needs to get done. Over time, the opportunity is yours to shape this role as we grow.',
        skills: ['Django', 'Javascript'],
        type: ['Remote', 'Contract'],
        location: 'London',
    },
    {
        id: '6',
        title: 'Junior Backend Developer',
        company:'Gear4Music',
        description: 'As a JavaScript junior developer, you will be responsible for Google Ads API developments and the implementation and maintenance of scripts, as well as reporting automation. These solutions will work to automate targeting, data sourcing and optimisation across multiple Google Ads accounts. Working closely with our marketing executives, you will help other SEM team members design scripts, automate & optimise their PPC accounts.',
        skills: ['Javascript'],
        type: ['Remote'],
        location: 'York YO26',
    },
    {
        id: '7',
        title: 'Production Manager',
        company:'BBC',
        description: 'Panorama is a ground breaking current affairs investigative series and we are looking for an experienced Production Manager with experience of managing a large portfolio or strand to join the team. Panorama produces some hard hitting investigations from undercover reporting to high risk filming in hostile countries covering a wide range content – experience of similar would be an advantage. You will work closely with third parties and Indies that are commissioned. Panorama produces 39 half hours and 7 one hours per year produced either inhouse London, Belfast, Regions or by Indies. This is an exciting opportunity for the right person to join the team.',
        skills: ['Management'],
        type: ['Contract'],
        location: 'London W1A',
    },
    {
        id: '8',
        title: 'Software Engineer',
        company:'Alliants',
        description: 'This position will see you working with an experienced team of developers, to help global brands improve their customer experiences through technology.',
        skills: ['Unit tests', 'Git', 'Node Js'],
        type: ['Remote'],
        location: 'Southampton',
    },
    {
        id: '9',
        title: 'Backend Developer',
        company:'KOBAS',
        description: 'The Kobas team provides Software-as-a-Service to the hospitality industry, transforming operational routines from dull, spreadsheet-based grind to quick, point-and-click management, across our core product pillars: In-Venue, Operations, Customers, Teams and Insights. Our software helps businesses process millions of pounds of sales each year. We unite with our clients so that they can benefit from our industry-leading technology, as well as ensuring that best practices can be followed, sharing knowledge amongst our clients, providing insight, and achieving maximum ROI.',
        skills: ['AWS', 'PHP'],
        type: ['Remote', 'Contract'],
        location: 'Home Based',
    },
    {
        id: '10',
        title: 'Software Developer',
        company:'Sainsburys',
        description: 'As a Software Engineer, you will build and maintain a suite of high performant and robust APIs that provide an outstanding user experience for our customers. You will work as part of an agile development team, helping to build a high performing culture where quality matters and delivery happens at pace.',
        skills: ['NodeJS', 'Typescript'],
        type: ['Full Time'],
        location: 'Edinburgh',
    },
]

export default {
    JOBS_DATA,
}