module.exports = {
    collectCoverageFrom: [
        '**/*.{js,jsx,ts,tsx}',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/.next/**',
        '!**/coverage/**',
        '!**/config/**',
        '!**/next.config.js',
        '!**/jest.config.js',
        '!**/postcss.config.js',
        '!**/tailwind.config.js',
    ],
    moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
    moduleNameMapper: {
        '@config/(.*)$': '<rootDir>/config/$1',
        '@logger': '<rootDir>/logger.config.ts',
        '@mocks/(.*)$': '<rootDir>/__mocks__/$1',
        '@pages/(.*)$': '<rootDir>/pages/$1',
        '@data': '<rootDir>/data.ts',
        '@tests/(.*)$': '<rootDir>/__tests__/$1',
        '^.+\\.(css)$': '<rootDir>/__mocks__/styleMock.js',
        '^.+\\.(jpg|jpeg|png|gif|webp|svg)$': `<rootDir>/__mocks__/fileMock.js`,
        '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
        '^@/common/(.*)$': '<rootDir>/components/common/$1',
        '^@/layout/(.*)$': '<rootDir>/components/layout/$1',
        '^@/pageComponents/(.*)$': '<rootDir>/components/pageComponents/$1',
    },
    preset: 'ts-jest',
    setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
    testEnvironment: 'jsdom',
    testPathIgnorePatterns: [
        '<rootDir>/node_modules/',
        '<rootDir>/.next/',
        '<rootDir>/coverage/',
        '<rootDir>/config/',
        '<rootDir>/next.config.js',
        '<rootDir>/jest.config.js',
        '<rootDir>/postcss.config.js',
        '<rootDir>/tailwind.config.js',
    ],
    transform: {
        '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
    },
    transformIgnorePatterns: ['/node_modules/', '^.+\\.module\\.(css)$'],
};
